feat/jwt-token-provider-juhyun
spring-problem/spring-login pull request #18
Opened 2023-10-12 14:35 UTC by juhyun-99

2023-10-12 14:40 UTC, junyoung-choe commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +                  @Value("${jwt.token-validity-in-seconds}") long expireTime){
어떻게 secret 과 expireTime을 가져오셨는지 궁금합니다

2023-10-14 12:29 UTC, junyoung-choe commented on build.gradle
> +    runtimeOnly "io.jsonwebtoken:jjwt-impl:0.11.5"
JWT 를 사용할때 Impl을 사용하지 않고 API를 통한 상위의 API를 사용하기 위함이 맞을까요?

2023-10-14 12:29 UTC, junyoung-choe commented on build.gradle
> +    runtimeOnly "io.jsonwebtoken:jjwt-jackson:0.11.5"
제가 해당 라이브러리를 찾아 봤을때는 JWT 데이터를 JAVA 객체로 변환하거나 반대 과정을 지원하는것이라고 하는데 어떤 기능을 위해서 사용하셨는지 궁금합니다.

2023-10-14 12:31 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +                  @Value("${jwt.token-validity-in-seconds}") long expireTime){
네 yml 파일에서 직접 값을 바로 가져오기 위해서 사용했습니다.

2023-10-14 12:36 UTC, juhyun-99 commented on build.gradle
> +    runtimeOnly "io.jsonwebtoken:jjwt-impl:0.11.5"
요구사항에 맞춰 0.9. jjwt 라이브러리 버전 0.11.5 사용하기 위해서 추가했습니다.

2023-10-14 12:37 UTC, juhyun-99 commented on build.gradle
> +    runtimeOnly "io.jsonwebtoken:jjwt-impl:0.11.5"
> JWT 를 사용할때 Impl을 사용하지 않고 API를 통한 상위의 API를 사용하기 위함이 맞을까요?

요구사항에 맞춰 0.9.1이 아닌 jjwt 라이브러리 버전 0.11.5 사용하기 위해서 추가했습니다.

2023-10-14 12:37 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +                  @Value("${jwt.token-validity-in-seconds}") long expireTime){
> 저는 JwtConfig 를 사용해서 Jwt 관련 설정 값들을 불러왔는데 @value를 이용해서 생성자나 컴파일 과정을 생략하시려고 사용한게 맞을까요?

네 yml 파일에서 직접 값을 바로 가져오기 위해서 사용했습니다.

2023-10-14 12:48 UTC, juhyun-99 commented on build.gradle
> +    runtimeOnly "io.jsonwebtoken:jjwt-jackson:0.11.5"
> 제가 해당 라이브러리를 찾아 봤을때는 JWT 데이터를 JAVA 객체로 변환하거나 반대 과정을 지원하는것이라고 하는데 어떤 기능을 위해서 사용하셨는지 궁금합니다.

implementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.5'
는 요구사항에 맞춰  0.9.1이 아닌 jjwt 라이브러리 버전 0.11.5 사용하기 위해서 추가했습니다.
하지만 여기서 이것을 추가한 후 실행을 하게 되면 JwtTest에서 provider.generateToken(member)을 하게 되면 오류가 나게 됩니다.

TokenProvider에 generateToken메소드에서 사용한 Jwts.builder()때문인데요. 
builder()메소드를 보면 DefaultjwtBuilder 클래스를 인스턴스화를 시도하는데 그 클래스가 없기 때문에 오류가 발생하게 됩니다.
그래서 컴파일 시에는 이 클래스가 없어도 문제가 없지만, 런타임시에 이 클래스가 없기 때문에 오류가 발생하게 됩니다. 
그렇기 때문에 runtimeOnly "io.jsonwebtoken:jjwt-impl:0.11.5" 를 build.gradle에 추가하여 주었습니다.

하지만 이것을 추가해도 TokenProvider에 generateToken메소드의 compact() 에서 오류가 발생하는데
compact()를 보면 LegacyServices.loadFirst(Serializer.class); 를 호출하는 것을 볼 수가 있습니다.
loadFirst메소드를 보면 Serializer.class를 인스턴스화를 시도하고 있습니다.
CLASS_LOADER_ACCESSORS 를 사용하여 Serializer.class 구현체를 찾아보지만 그 구현체가 없기 때문에 오류가 발생하게 됩니다. 따라서 runtimeOnly "io.jsonwebtoken:jjwt-jackson:0.11.5"를 넣어주었습니다.

2023-10-14 13:23 UTC, bluepeng9 requested changes

2023-10-14 13:23 UTC, bluepeng9 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +                .signWith(SignatureAlgorithm.HS256, secret)
현재 라이브러리 버전에서는 deprecate 되어서 다른 메서드를 찾아보는건 어떨까요?

2023-10-14 13:23 UTC, bluepeng9 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +        claims.put("userID", id);
subject 대신 userId 라는 새로운 키 값을 사용한 이유가 궁금합니다

2023-10-14 13:23 UTC, bluepeng9 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +    private long expireTime;
생성자 주입 방식을 사용하고 있기 때문에 final 을 붙이는건 어떨까요?

2023-10-14 13:23 UTC, bluepeng9 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +    private final String alg = "HS256";
signWith 에서 사용하는 SignatureAlgorithm 와 연관이 있고, 값을 갖고오는 메서드도 있으니 SignatureAlgorithm 타입으로 사용해보는 건 어떨까요?

2023-10-14 13:23 UTC, bluepeng9 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +                         @Value("${jwt.token-validity-in-seconds}") String expireTime){
token-validity-in-seconds 는 초를 의미하는 거 같은데, 따로 처리가 안 되어 있어서 초 값으로 동작하지 않는 거 같아요

2023-10-14 13:23 UTC, bluepeng9 commented on build.gradle
> +    implementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.5'
다른 문장과 형식이 일관성을 맞추기 위해 short 버전으로 적는건 어떨까요?

2023-10-14 13:23 UTC, bluepeng9 commented on build.gradle
> +//    implementation "io.jsonwebtoken:jjwt:0.9.1"
이 부분을 아래 jwt 라이브러리로 교체하면 좋을 거 같아요

2023-10-14 13:27 UTC, juhyun-99 commented on build.gradle
> +//    implementation "io.jsonwebtoken:jjwt:0.9.1"
넵 지우도록 하겠습니다.

2023-10-14 13:31 UTC, juhyun-99 commented on build.gradle
> +    implementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.5'
넵 short 버전으로 수정하도록 하겠습니다.

2023-10-14 13:31 UTC, juhyun-99 commented on build.gradle
> +    implementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.5'
> 넵 short 버전으로 수정하도록 하겠습니다.

넵 short 버전으로 수정하도록 하겠습니다.

2023-10-14 13:31 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +                         @Value("${jwt.token-validity-in-seconds}") String expireTime){
> token-validity-in-seconds 는 초를 의미하는 거 같은데, 따로 처리가 안 되어 있어서 초 값으로 동작하지 않는 거 같아요

해당 부분은 찾아보고 수정하도록 하겠습니다.

2023-10-14 13:32 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +    private final String alg = "HS256";
> signWith 에서 사용하는 SignatureAlgorithm 와 연관이 있고, 값을 갖고오는 메서드도 있으니 SignatureAlgorithm 타입으로 사용해보는 건 어떨까요?

SignatureAlgorithm 타입을 찾아본 이후에 적용해보도록 하겠습니다.

2023-10-14 13:32 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +    private long expireTime;
> 생성자 주입 방식을 사용하고 있기 때문에 final 을 붙이는건 어떨까요?

넵 추가하도록 하겠습니다.

2023-10-14 13:32 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +                .signWith(SignatureAlgorithm.HS256, secret)
> 현재 라이브러리 버전에서는 deprecate 되어서 다른 메서드를 찾아보는건 어떨까요?

다른 메서드를 찾아본 후 수정하겠습니다.

2023-10-14 13:36 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +        claims.put("userID", id);
setSubject() 메소드를 방금 처음 알게되어서 공부해본 후에 적용하도록 하겠습니다.

2023-10-15 07:29 UTC, bluepeng9 requested changes

2023-10-15 07:29 UTC, bluepeng9 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +    private final SignatureAlgorithm alg = SignatureAlgorithm.valueOf("HS256");
valueOf 는 컴파일 시점에 에러를 잡을 수 없으니, 다른 방식으로 값을 넣는건 어떨까요?

2023-10-15 07:29 UTC, bluepeng9 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +                .signWith(secret, SignatureAlgorithm.HS256)
alg 라는 전역변수가 선언 되어 있으니, 그 값을 활용해보는 건 어떨까요?

2023-10-15 07:48 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +                .signWith(secret, SignatureAlgorithm.HS256)
알겠습니다 수정하겠습니다!!

2023-10-15 07:49 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +    private final SignatureAlgorithm alg = SignatureAlgorithm.valueOf("HS256");
> valueOf 는 컴파일 시점에 에러를 잡을 수 없으니, 다른 방식으로 값을 넣는건 어떨까요?

SignatureAlgorithm.HS256을 알고 있었는데 생각을 못했습니다. 이 방법으로 바꾸도록 하겠습니다.

2023-10-15 07:49 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/global/util/TokenProvider.java
> +                .signWith(secret, SignatureAlgorithm.HS256)
> alg 라는 전역변수가 선언 되어 있으니, 그 값을 활용해보는 건 어떨까요?

알겠습니다 수정하겠습니다!!

2023-10-15 08:36 UTC, junyoung-choe approved these changes

2023-10-15 08:36 UTC, bluepeng9 approved these changes

2023-10-15 08:37 UTC, merged