Feat/member cookie controller junyoung
spring-problem/spring-login pull request #5
Opened 2023-09-25 13:58 UTC by junyoung-choe

2023-09-25 14:17 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
> +        return "index";
memberService의 login 메소드에서 login 실패시에 null값이 반환되면 어디로 url을 return할지도 추가해야할 것 같습니다.

2023-09-26 05:04 UTC, junyoung-choe commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
> +        response.addCookie(cookie);
> 어차피 삭제할 쿠키인데 null값으로 설정하는 이유는 무엇인가요?
해당 이름으로 만든 쿠키를 객체로 받아오고 해당 쿠키의 유효 시간을 0으로 삭제하기 위해서 입니다. 제가 알기로는 null 객체를 넣어 주는 것만으로 쿠키를 삭제하는 효과를 나타냅니다.

2023-09-26 05:06 UTC, junyoung-choe commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
> +        return "index";
> memberService의 login 메소드에서 login 실패시에 null값이 반환되면 어디로 url을 return할지도 추가해야할 것 같습니다.

그 부분을 추가하지 못했네요 로그인이 실패하는 로직에 대해서 추가 해보겠습니다.

2023-09-26 05:09 UTC, junyoung-choe commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
>      }
이 부분은 제가 부족한 부분이 있었습니다. 어제 주현님의 코드를 보고 학습후에 재작성 하였습니다.

2023-09-26 05:09 UTC, junyoung-choe commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
>      }
> 사용자가 url을 통해서 login에 접근하려고 했을 때 이미 로그인 상태인 유저(cookie or session 값이 있는 user)는 login에 접근하지 못하게 해야하지 않나요?

이 부분은 제가 부족한 부분이 있었습니다. 어제 주현님의 코드를 보고 학습후에 재작성 하였습니다.

2023-09-26 05:26 UTC, bluepeng9 commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
> +        response.addCookie(cookie);
https://stackoverflow.com/a/9828731 관련 내용입니다

2023-09-26 06:26 UTC, bluepeng9 requested changes

2023-09-26 14:47 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
> +//    }
memberService는 나중에 변경될 일이 없으니 final 생성자 주입으로 바꾸는게 어떨까요?

2023-09-26 14:47 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
> +//    }
memberService는 나중에 변경될 일이 없으니 final 생성자 주입으로 바꾸는게 어떨까요?

2023-09-26 14:47 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
login과 logout 메소드에서 url을 그냥 return 할 경우 새로고침은 가장 마지막에 요청한 Url 방식을 그대로 반복하기 때문에 return 부분을 수정 해야할 것 같습니다.

2023-09-26 14:50 UTC, bluepeng9 commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
> +//    }
더해서 RequiredArgsConstructor 사용하는 건 어떨까요

2023-09-26 15:07 UTC, junyoung-choe commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
> +    @Autowired
> MemberCookieController 는 Config 에서 주입되고 있기 때문에, service 역시 주입받는게 어떨까요?

알려주신 방법으로 config에서 컨트롤러에서 서비스 객체를 주입 해줬습니다.

2023-09-26 15:07 UTC, junyoung-choe commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
> +@ComponentScan
> Config 에서 주입하고 있기 때문에 불필요합니다

확인했습니다.

2023-09-26 15:08 UTC, junyoung-choe commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
> +//    }
> 더해서 RequiredArgsConstructor 사용하는 건 어떨까요

넵 알겠습니다.

2023-09-26 15:19 UTC, juhyun-99 commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
> +                    return "redirect:/";
여기서 왜 redirect를 사용했는지 알 수 있을까요?

2023-10-04 13:15 UTC, bluepeng9 requested changes

2023-10-04 13:15 UTC, bluepeng9 commented on src/main/java/com/example/springlogin/member/controller/MemberCookieController.java
> +        Optional<Member> member = Optional.ofNullable(memberService.login(loginParam));
이미 null 이 날아올 수 있는 상황이기 때문에 근본적으로 memberService 자체에서 Optional 을 주는 건 어떨까요?

2023-10-04 13:44 UTC, bluepeng9 commented on src/main/java/com/example/springlogin/member/service/MemberServiceImpl.java
>          Optional<Member> member = Optional.ofNullable(memberRepository.findByEmailAndPassword(param.getEmail(), param.getPassword()));
마찬가지로 Repository 에서도 Optional 로 return 해주는 게 좋아보여요

2023-10-04 13:56 UTC, bluepeng9 commented on src/main/java/com/example/springlogin/member/service/MemberServiceImpl.java
> +        if(!member.isPresent())  return null;
어차피 없으면 Optional 을 return 하기 때문에 member 를 바로 return 해주는게 좋아보여요

2023-10-04 14:03 UTC, bluepeng9 approved these changes

2023-10-04 14:06 UTC, merged